#!/usr/bin/env node

const path = require('node:path');
const fs = require('node:fs');

const project_root = path.resolve(__dirname, '..');

const file = path.join(project_root, 'example', 'src', 'env.ts');
const content = `// This file is automatically generated. The user needs to manually fill in the necessary parameters.\n
export const test = true;
export const isDevMode = true;
export const appKey = '';
export const accountType = ''; // agora or easemob
export const agoraAppId = '';
export const account = [{ id: '', token: '' }];
`;
if (fs.existsSync(file) === false) {
  fs.writeFileSync(file, content, 'utf-8');
}
